---

# email record number notification 

- name: copy record number notification email file
  copy:
    src: "{{ migrid_copy_record_number_email_notification_file }}"
    dest: "{{ migrid_state_directory }}/gdp_home/"
    owner: "{{ migrid_user }}"
    group: "{{ migrid_user }}"
  when: migrid_copy_record_number_email_notification_file is file

# any changes to notify email configurations: