---
# this will start the containers in the docker-compose start fashion

- name: Running docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{migrid_root}}"
    build: never
    profiles: "{{ migrid_start_containers_profiles }}"
    recreate: "{{ migrid_start_containers_recreate }}"
