---
# copy cert files into migrid_root directory
# depends on migrid-baseline

# If certs is set to external directory, link it into the docker-migrid directory
- name: Link cert to external directory

  file:
    src: "{{ migrid_certs }}"
    dest: "{{ migrid_root }}/certs"
    state: link
  when: not migrid_certs is search(migrid_root)

- name: Create directoris for certificates
  file:
    path: "{{ migrid_certs }}/MiG/*.{{ migrid_copy_cert_files_domain }}"
    owner: "{{ migrid_user }}"
    group: "{{ migrid_user }}"
    state: directory
    mode: "0755"

- name: Copy files certs to server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ migrid_user }}"
    group: "{{ migrid_user }}"
    mode: "0400"
    remote_src: "{{ migrid_copy_cert_files_remote_src | default(omit) }}"
  loop: "{{ migrid_copy_cert_files }}"
  when: migrid_copy_cert_files is iterable

# relative symbolic links can be created by having a relative src

- name: Create symbolic links for directories
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ migrid_cert_dir_links }}"

- name: Create symbolic links for files
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ migrid_cert_file_links }}"
