---
# copy cert files into migrid_root directory
# depends on migrid-baseline

# This is to support that a server can have another server name than the DOMAIN in env file
- name: find domain for migrid environment
  shell:
    cmd: "grep ^DOMAIN= /opt/migrid/docker-migrid/.env | awk -F'=' '{print $2}'"
  register: results

- name: Set domain
  set_fact:
    migrid_domain: "{{results.stdout}}"

# If certs is set to external directory, link it into the docker-migrid directory
- name: Link cert to external directory

  file:
    src: "{{ migrid_certs }}"
    dest: "{{ migrid_root }}/certs"
    state: link
  when: not migrid_certs is search(migrid_root)

- name: Create directoris for certificates
  file:
    path: "{{ migrid_certs }}/MiG/*.{{ migrid_copy_cert_files_domain }}"
    owner: "{{ migrid_user }}"
    group: "{{ migrid_user }}"
    state: directory
    mode: "0755"

- name: Copy files certs to server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ migrid_user }}"
    group: "{{ migrid_user }}"
    mode: "0400"
    remote_src: "{{ migrid_copy_cert_files_remote_src | default(omit) }}"
  loop: "{{ migrid_copy_cert_files }}"
  when: migrid_copy_cert_files is iterable

# relative symbolic links can be created by having a relative src

- name: Create symbolic links for directories
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ migrid_cert_dir_links }}"

- name: Create symbolic links for files
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ migrid_cert_file_links }}"

# copy selfsigned root certificate to external-certificates/

- name: Create directory for external-certificates/ if needed
  file:
    path: "{{ migrid_root }}/external-certificates"
    owner: "{{ migrid_adm }}"
    group: "{{ migrid_adm }}"
    state: directory
    mode: "0755"
  when: migrid_selfsigned_certificates==true

- name: Copy selfsigned certificate if needed
  copy:
    src: "{{migrid_selfsigned_cert_file}}"
    dest: "{{ migrid_root }}/external-certificates/{{migrid_selfsigned_cert_file | basename }}"
    owner: "{{ migrid_user }}"
    group: "{{ migrid_user }}"
    mode: "0400"
  when: migrid_selfsigned_certificates==true

# persistent file

- name: Set .persistent file if defined
  file:
    path: "{{ migrid_root }}/certs/.persistent"
    owner: "{{ migrid_user }}"
    group: "{{ migrid_user }}"
    mode: 0644
    state: touch
  when: migrid_cert_persistant==true

# using https://ssl-config.mozilla.org/ffdhe4096.txt as contents for dhparams.pem
- name: Copy dhparams.pem into certs/
  copy:
    src: dhparams.pem
    dest: "{{ migrid_certs }}"
    owner: "{{ migrid_user }}"
    group: "{{ migrid_user }}"