---
# install promtail for sending logs to grafana loki
- name: Import user create task
  import_tasks:
    file: user.yml

- name: Create position directory
  file:
    path: /var/log/promtail
    owner: promtail
    group: promtail
    mode: "0755"
    state: directory

- name: install Promtail
  apt:
    deb: https://github.com/grafana/loki/releases/download/v{{promtail_version}}/promtail_{{promtail_version}}_amd64.deb
  notify: restart-promtail

- name: Copy configuration file
  template:
    src: config.yml.j2
    dest: /etc/promtail/config.yml
  notify: restart-promtail

- name: Enable Promtail
  systemd:
    name: promtail
    enabled: true
    state: started
