---
# install promtail for sending logs to grafana loki
- name: Import user create task
  import_tasks:
    file: user.yml

- name: Create position directory
  file:
    path: /var/log/promtail
    owner: promtail
    group: promtail
    mode: "0755"
    state: directory

- name: install Promtail (debian)
  apt:
    deb: https://github.com/grafana/loki/releases/download/v{{promtail_version}}/promtail_{{promtail_version}}_amd64.deb
  notify: stop-promtail
  when: ansible_os_family == "Debian"

- name: Install Promtail (RedHat)
  dnf:
    name: https://github.com/grafana/loki/releases/download/v{{promtail_version}}/promtail-{{promtail_version}}.x86_64.rpm
    state: present
    disable_gpg_check: true
  notify: stop-promtail
  when: ansible_os_family == 'RedHat'

- name: Copy configuration file
  template:
    src: config.yml.j2
    dest: /etc/promtail/config.yml
  notify: stop-promtail

- name: Setup Promtail in disabled state
  systemd:
    name: promtail
    enabled: false
    state: stopped
