---
- name: run create user command in container
  community.docker.docker_container_exec:
    container: "{{ migrid_create_users_container }}"
    command: "./createuser.py -v {{ item.options | default('') }} {{ item.full_name}} {{ item.organization }} {{ item.state }} {{ item.country }} {{ item.email }} '{{ item.comment | default ('created by Ansible') }}' {{ item.password }}"
    chdir: "/home/mig/mig/server"
    user: "{{ migrid_create_users_container_user }}"
  loop: "{{ migrid_create_users }}"
