---
- name: Install needed packages
  package:
    name: logrotate
    state: present
    update_cache: true
  become: yes

- name: Copy migrid logrotate file
  template:
    src: migridlog.j2
    dest: /etc/logrotate.d/migridlog
  notify: restart-logrotate

- name: Copy lustre_exporter logrotate file
  template:
    src: lustre_exporter.j2
    dest: /etc/logrotate.d/lustre_exporter
  notify: restart-logrotate

- name: Enable logrotate (Debian)
  systemd:
    name: logrotate
    enabled: true
    state: started
  when: ansible_os_family == "Debian"

- name: Enable logrotate (Redhat)
  cron:
    name: mirgid-logrotate
    user: root
    minute: "10"
    hour: "4"
    job: logrotate -f /etc/logrotate.conf
  when: ansible_os_family == "RedHat"
