---
# role for installing logstash for consuming the gdp.log file. 
# We want to be sure that no data is lost during logfile consuming, and that everything ends in loki
# requires:
#   setup_vars
#   community.general (.logstash_plugin) version 7.5.0 or greater
#   promtail_migrid   requires that user that you defined for logscraping on lustre mds is defined on server

#import promtail user task to ensure the user used here is available (reusing the promtail user for lustre access)
- name: Import user create task
  import_tasks:
    file: ../../promtail_migrid/tasks/user.yml

#FIXME: redhat version of getting logstash
- name: Ensure Elastic keys are available (debian)
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_os_family == "Debian"

- name: Install Elastic OSS repo (debian)
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/oss-{{ migrid_elastic_release }}.x/apt stable main
  when: ansible_os_family == "Debian"

- name: Install logstash (debian)
  apt:
    name: logstash-oss
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install logstash-output-loki
  community.general.logstash_plugin:
    name: logstash-output-loki
    state: present

- name: Set the user for logstash during execution
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/logstash.service
    regexp: '^User='
    line: "User={{logstash_user}}"
  #notify: restart-logstash

- name: Set the group for logstash during execution
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/logstash.service
    regexp: '^Group='
    line: "Group={{logstash_user}}"
  #notify: restart-logstash

- name: Ensure all files are owned by {{logstash_user}} in {{logstash_config_path_logs}}
  file:
    path: "{{logstash_config_path_logs}}"
    owner: "{{logstash_user}}"
    group: "{{logstash_user}}"
    recurse: true

- name: Ensure all files are owned by {{logstash_user}} in {{logstash_config_path_data}}
  file:
    path: "{{logstash_config_path_data}}"
    owner: "{{logstash_user}}"
    group: "{{logstash_user}}"
    recurse: true

#when touching a file in lustre you cannot set the user or group.
- name: touch {{migrid_state_directory}}/log/gdp.sincedb
  file:
    path: "{{migrid_state_directory}}/log/gdp.sincedb"
    state: touch
    mode: 0666

- name: Copy logstash.yml configuration file
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
    owner: root
    group: root
    mode: 0644
  #notify: restart-logstash

- name: Copy migrid-gdp-log.conf to pipeline configuration catalog for logstash
  template:
    src: migrid-gdp-log.conf.j2
    dest: /etc/logstash/conf.d/migrid-gdp-log.conf
    owner: root
    group: root
    mode: 0644
  #notify: restart-logstash

- name: Setup logstash in disabled state
  systemd:
    name: logstash
    enabled: false
    state: stopped