---
# only use logstash if the server is a SiF server. Here i know that from my inventory.yml
- name: Import logstash task if needed
  import_tasks:
    file: logstash.yml
  when: '"sif" in group_names'