---
migrid_copy_cert_files_domain: "{{ migrid_domain }}"
migrid_copy_cert_files_remote_src: false
migrid_copy_cert_files:
  - src: manual/certs/{{ ansible_hostname }}/
    dest: "{{ migrid_certs }}/MiG/*.{{ migrid_copy_cert_files_domain }}"

# in order to support KU way of using copy_cert_files configuration this is placed here.
# This sets what file contains the selfsigned certificate you want to load into external-certificates directory
# Since migrid already uses cerificates we just reuse the pem for the server.
migrid_selfsigned_cert_file: "{{migrid_copy_cert_files[0].src}}/server.ca.pem"

# do not do anything in the cert directory
migrid_cert_persistant: true

migrid_cert_dir_links:
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}", dest: "{{ migrid_certs }}/anon.{{ migrid_copy_cert_files_domain }}" }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}", dest: "{{ migrid_certs }}/cert.{{ migrid_copy_cert_files_domain }}" }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}", dest: "{{ migrid_certs }}/*.{{ migrid_copy_cert_files_domain }}" }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}", dest: "{{ migrid_certs }}/ext.{{ migrid_copy_cert_files_domain }}" }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}", dest: "{{ migrid_certs }}/int.{{ migrid_copy_cert_files_domain }}" }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}", dest: "{{ migrid_certs }}/io.{{ migrid_copy_cert_files_domain }}" }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}", dest: "{{ migrid_certs }}/www.{{ migrid_copy_cert_files_domain }}" }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}", dest: "{{ migrid_certs }}/oid.{{ migrid_copy_cert_files_domain }}" }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}", dest: "{{ migrid_certs }}/sid.{{ migrid_copy_cert_files_domain }}" }

migrid_cert_file_links:
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}/cacert.pem",    dest: "{{ migrid_certs }}/cacert.pem",     }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}/combined.pem",  dest: "{{ migrid_certs }}/combined.pem",   }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}/combined.pub",  dest: "{{ migrid_certs }}/combined.pub",   }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}/crl.pem",       dest: "{{ migrid_certs }}/crl.pem",        }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}/server.ca.pem", dest: "{{ migrid_certs }}/server.ca.pem",  }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}/server.crt",    dest: "{{ migrid_certs }}/server.crt",     }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}/server.key",    dest: "{{ migrid_certs }}/server.key",     }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}/combined.pem.sha256",  dest: "{{ migrid_certs }}/combined.pem.sha256",   }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}/combined.pub.md5",  dest: "{{ migrid_certs }}/combined.pub.md5",   }
  - { src: "MiG/*.{{ migrid_copy_cert_files_domain }}/combined.pub.sha256",  dest: "{{ migrid_certs }}/combined.pub.sha256",   }