---

# alloy installation is based on
# https://github.com/grafana/grafana-ansible-collection/tree/main

- name: Import user create task
  import_tasks:
    file: user.yml

- name: Install Alloy (RedHat)
  dnf:
    name: "https://github.com/grafana/alloy/releases/download/v{{ alloy_version }}/alloy-{{ alloy_version }}-1.amd64.rpm"
    state: present
    disable_gpg_check: true
  notify: stop-alloy
  when: ansible_os_family == 'RedHat'

- name: install Alloy (debian)
  apt:
    deb: "https://github.com/grafana/alloy/releases/download/v{{ alloy_version }}/alloy-{{ alloy_version }}-1.amd64.deb"
  notify: stop-alloy
  when: ansible_os_family == "Debian"

- name: Copy configuration file
  template:
    src: config.alloy.j2
    dest: /etc/alloy/config.alloy
  notify: stop-promtail

- name: Update CUSTOM_ARGS for alloy
  lineinfile:
    path: /etc/sysconfig/alloy
    regexp: "^CUSTOM_ARGS"
    line: 'CUSTOM_ARGS="--server.http.listen-addr={{ ansible_facts[promtail_loki_net]['ipv4']['address'] }}:3102"'

- name: Setup Alloy in disabled state
  systemd:
    name: alloy
    enabled: false
    state: stopped