---

#user has to exist also on mds lustre server
- name: Add alloy group
  group:
    name: alloy
    gid: "{{alloy_user_gid}}"
    state: present

- name: Add alloy users
  user:
    name: alloy
    comment: alloy user
    uid: "{{alloy_user_uid}}"
    group: alloy
    shell: /bin/bash
    password_lock: true