---
# old docker-compose 

- name: Get infos on container
  community.docker.docker_container_info:
    name: migrid
  register: migrid_container

- name: Check if migrid container exists
  fail:
    msg: MiGrid container already exists, cannot continue!
  when: migrid_container.exists

- name: Running docker-compose up
  community.docker.docker_compose:
    profiles: "{{ migrid_start_containers_profiles | default(omit) }}"
    project_src: "{{ migrid_root }}"
    build: false
    recreate: always

- name: pause
  pause:
    seconds: 10

- name: Stopping containers
  community.docker.docker_compose:
    project_src: "{{ migrid_root }}"
    build: false
    state: absent
    stopped: true