---
# check if directory migrid_copy_email_notifications_dir exists
- name: Check if migrid_copy_email_notifications_dir already exists
  stat:
    path: "{{migrid_copy_email_notifications_dir}}"
  register: st

# This will only run if gocryptfs is not configured
- name: Import notifications task if needed
  import_tasks:
    file: notifications.yml
  when: st.stat.exists==true
